### PR TITLE
Upgrade Parent POM to 3.2 and Jackson libs to 2.8.10

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just an ongoing update of the library.

Changelogs:

- 2.8.8: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.8
- 2.8.9: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.9
- 2.8.10: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.10

Full diff:
- https://github.com/FasterXML/jackson-databind/compare/jackson-databind-2.8.7...jackson-databind-2.8.10

@reviewbybees @stephenc @ndeloof

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
We could, but in such case we need to establish the binary compatility
checkz and so on.

**Comment by ndeloof** [comment]
"binary compatility checks" ? Don't we just upgrade to latest ? If jackson at some point introduces a compatibility break, does this mean jenkins ecosystem will get stick with an obsolete version ?

**Comment by oleg-nenashev** [comment]
@ndeloof It is TBD, but I definitely want us to know about the compatibility breakage BEFORE the plugin gets released, so that's the reason why I do not have an automatic release logic

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
