### PR TITLE
[JENKINS-50201] Added jackson-module-jaxb-annotations

### PR DESCRIPTION
**Pull request by agentgonzo**
See [JENKINS-50201](https://issues.jenkins-ci.org/browse/JENKINS-50201)

@reviewbybees

### CODE REVIEW

**Comment by batmat** [comment]
@agentgonzo can you please provide a bit more explanations (and a link to the associated JIRA) as to what we are trying to achieve here? Thanks!

**Comment by agentgonzo** [comment]
@jtnord can probably provide more context, but it's about ensuring that jackson dependencies get managed through this plugin, rather than pulled in randomly at different versions via explicit dependencies.

**Comment by agentgonzo** [comment]
I think it's that https://github.com/jenkinsci/kubernetes-credentials-provider-plugin has a transitive dependency on jaxb-annotations through the fabric8.io libraries that should be ideally managed via the jackson2-api plugin:

```
[INFO] --- maven-dependency-plugin:3.0.0:tree (default-cli) @ kubernetes-credentials-provider ---
[INFO] com.cloudbees.jenkins.plugins:kubernetes-credentials-provider:hpi:0.10-SNAPSHOT
[INFO] \- io.fabric8:kubernetes-client:jar:3.1.8:compile
[INFO]    \- io.fabric8:kubernetes-model:jar:2.0.4:compile
[INFO]       \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.7.5:compile
```

**Comment by jtnord** [comment]
related to [JENKINS-50202](https://issues.jenkins-ci.org/browse/) (include `jackson-dataformat-yaml`)

**Comment by agentgonzo** [comment]
I don't have permission to merge this PR

**Comment by batmat** [comment]
@angelman that's expected.
Unless you become the maintainer from the Jenkins Project standpoint, what just happened is the compulsory review of bees.
Now you need to find who the current maintainers are, and ask for a possible merge and release.

**Pull request merged**
